fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /
    #resource: '@AppBundle/Controller/'
    #type: annotation

